### ISSUE TITLE
No such file: concepts_subgraph.pkl

### ISSUE THREAD

**Issue by Sweetest316** [whonor/IPNR#1]
Hello, author, I am very interested in your project, and I have also conducted research, but when I am training, I have encountered a problem: 
Traceback (most recent call last):
  File "main.py", line 80, in <module>
    mind_corpus = MIND_Corpus(config)
  File "E:\HH\IPNR-main\IPNR-source\MIND_corpus.py", line 290, in __init__
    MIND_Corpus.preprocess(config)
  File "E:\HH\IPNR-main\IPNR-source\MIND_corpus.py", line 233, in preprocess
    graph = pickle.load(open("../MIND-small/"+mode+"/concepts_subgraph.pkl", 'rb'))   # build by 02_build_edge_index.py
FileNotFoundError: [Errno 2] No such file or directory: '../MIND-small/train/concepts_subgraph.pkl'. 

It seems that the training.pkl file is missing, am I overlooking something? Or can you provide the file?

**Comment by whonor** [comment]
Sorry to see your question so late.  You can obtain this file through using codes related about 'conceptgraph' in the directory of Conceptgraph.
